acme_hello_homepage:
    pattern:  /hola/{name}/{creator}
    defaults: { _controller: AcmeHelloBundle:Default:index, creator: null }
acme_hello_aviso:
    path: /aviso-legal
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'AcmeHelloBundle:Static:aviso.html.twig'